### ISSUE TITLE
create footer

### ISSUE THREAD

**Issue by sanket0354** [sanket0354/world-mindz.com#2]
Background color black and text color white

**Comment by geekshubham** [comment]
Done with the Footer!!

[footer.css.txt](https://github.com/sanket0354/world-mindz.com/files/306138/footer.css.txt)
[footer.html.txt](https://github.com/sanket0354/world-mindz.com/files/306139/footer.html.txt)

**Comment by sanket0354** [comment]
will review it once ! After that close the issue

**Comment by sanket0354** [comment]
General Design Comments : 
- Modify the search bar similar to what is there in the header to make it consistent 
- Can you bit shorten the footer size, may be by 10-15 pixels , there is a lot of gap above and below and we are not going to have more content then this in the footer
- The name of the website is mind worldz
- Move the third part of footer to extreme right , just as the search bar in the header

General Code Comments : 
- Add comments in the code

Otherwise seems good
